package client_atm;

import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;


public class Main extends javax.swing.JFrame {

    User user;
    public Main() throws RemoteException, SQLException {
        initComponents();
        setLocationRelativeTo(null);
        user = new User();
        tfsoduht.setText(String.valueOf(user.bank.getAccount(Login.userInfo.get(0), Login.userInfo.get(1)).getBalance()));
        tfbalance.setText(tfsoduht.getText());
        inquiry();
        jTabbedPane1.addChangeListener((ChangeEvent e) -> {
            if(jTabbedPane1.getSelectedIndex()==5){
                new Login().setVisible(true);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfpw = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfpwag = new javax.swing.JPasswordField();
        btsave = new javax.swing.JButton();
        btBack2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfamount = new javax.swing.JTextField();
        btOk = new javax.swing.JButton();
        btCancelG = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfsoduht = new javax.swing.JTextField();
        tfBalance = new javax.swing.JTextField();
        btOk1 = new javax.swing.JButton();
        btCancelR = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbresult = new javax.swing.JLabel();
        lbten = new javax.swing.JLabel();
        lbaddress = new javax.swing.JLabel();
        lbphone = new javax.swing.JLabel();
        lbnumAcc = new javax.swing.JLabel();
        lbcmnd = new javax.swing.JLabel();
        lbsodu = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        tfpw1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfpwag1 = new javax.swing.JPasswordField();
        btsave1 = new javax.swing.JButton();
        btCancelD = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btOk2 = new javax.swing.JButton();
        btCancelC = new javax.swing.JButton();
        tfbalance = new javax.swing.JTextField();
        tfamount1 = new javax.swing.JTextField();
        tfnumAcc = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();

        jLabel1.setText("Nhập mật khẩu mới : ");

        jLabel5.setText("Nhập lại mật khẩu : ");

        btsave.setText("Save");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });

        btBack2.setText("Back");
        btBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBack2ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nhập số tiền gửi : ");

        tfamount.setToolTipText("");

        btOk.setText("Ok");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btCancelG.setText("Cancel");
        btCancelG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(tfamount, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btCancelG, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btCancelG, btOk});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfamount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelG, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gửi tiền", jPanel1);

        jLabel3.setText("Nhập số tiền cần rút : ");

        jLabel4.setText("Số dư hiện có : ");

        tfsoduht.setEditable(false);
        tfsoduht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsoduhtActionPerformed(evt);
            }
        });

        btOk1.setText("Ok");
        btOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOk1ActionPerformed(evt);
            }
        });

        btCancelR.setText("Cancel");
        btCancelR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(126, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfsoduht, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btOk1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btCancelR, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(130, 130, 130))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel4});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(tfBalance))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfsoduht, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOk1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelR, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4, tfsoduht});

        jTabbedPane1.addTab("Rút tiền", jPanel2);

        lbresult.setText("Thông tin của người dùng : ");

        lbten.setText("Họ tên : ");

        lbaddress.setText("Địa chỉ :");

        lbphone.setText("Số điện thoại : ");

        lbnumAcc.setText("Số tài khoản : ");

        lbcmnd.setText("Số cmnd : ");

        lbsodu.setText("Số dư : ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbresult)
                            .addComponent(lbcmnd)
                            .addComponent(lbsodu)
                            .addComponent(lbnumAcc)
                            .addComponent(lbphone, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 137, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbresult)
                .addGap(18, 18, 18)
                .addComponent(lbten)
                .addGap(18, 18, 18)
                .addComponent(lbaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbphone)
                .addGap(18, 18, 18)
                .addComponent(lbnumAcc)
                .addGap(18, 18, 18)
                .addComponent(lbcmnd)
                .addGap(18, 18, 18)
                .addComponent(lbsodu)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông tin tài khoản", jPanel4);

        jLabel6.setText("Nhập mật khẩu mới : ");

        jLabel7.setText("Nhập lại mật khẩu : ");

        btsave1.setText("Save");
        btsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsave1ActionPerformed(evt);
            }
        });

        btCancelD.setText("Cancel");
        btCancelD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btsave1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCancelD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfpw1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfpwag1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(126, 126, 126))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfpw1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfpwag1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelD)
                    .addComponent(btsave1))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Đổi mật khẩu", jPanel5);

        jLabel8.setText("Nhập  số tài khoản người nhận : ");

        jLabel10.setText("Nhập số tiền cần chuyển : ");

        jLabel11.setText("Số dư hiện có : ");

        btOk2.setText("Ok");
        btOk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOk2ActionPerformed(evt);
            }
        });

        btCancelC.setText("Cancel");
        btCancelC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelCActionPerformed(evt);
            }
        });

        tfbalance.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel11))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfamount1)
                            .addComponent(tfbalance)
                            .addComponent(tfnumAcc)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(btOk2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCancelC, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addGap(102, 102, 102))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfnumAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfamount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOk2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chuyển khoản", jPanel3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Đăng xuất", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inquiry() throws RemoteException, SQLException{
        setValue(user.bank.inquiry(Login.userInfo.get(0), Login.userInfo.get(1)));
    }
    private void setValue(ArrayList<String> result){
        lbten.setText(lbten.getText()+ result.get(0));
        lbaddress.setText(lbaddress.getText()+result.get(1));
        lbphone.setText(lbphone.getText()+result.get(2));
        lbnumAcc.setText(lbnumAcc.getText()+result.get(3));
        lbcmnd.setText(lbcmnd.getText()+result.get(4));
        lbsodu.setText(lbsodu.getText()+result.get(5));   
    }    
    private ArrayList<String> validation(){
        ArrayList<String> loi = new ArrayList<>();
        if(tfpw1.getText().equals("")||tfpwag1.getText().equals("")){
            loi.add("Bạn chưa điền đủ thông tin");
            return loi;
        }if(tfpw1.getText().length()<6){
            loi.add("Mật khẩu chứa ít nhất 6 kí tự");
            return loi;
        }
        if(!tfpw1.getText().equals(tfpwag1.getText())){
            loi.add("Mật khẩu không khớp");
            return loi;
        }
        return loi;
    }
     
    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        ArrayList<String> loi = validation();
        if(loi.isEmpty()){
            try {
                user.bank.doimatkhau(Login.userInfo.get(0), Login.userInfo.get(1),tfpw.getText());
                Login.userInfo.set(2, tfpw.getText());
                JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                tfpw.setText("");
                tfpwag.setText("");
            } catch (RemoteException | SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, loi.get(0), "Warning",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btsaveActionPerformed

    private void btBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBack2ActionPerformed

//        dispose();
    }//GEN-LAST:event_btBack2ActionPerformed

    private void btCancelCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelCActionPerformed
        tfnumAcc.setText("");
        tfamount1.setText("");
    }//GEN-LAST:event_btCancelCActionPerformed

    private void btOk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOk2ActionPerformed
        if(tfnumAcc.getText().equals("")||tfamount1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Bạn chưa điền đủ thông tin", "Warning",
                JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                ArrayList<String> loi = user.bank.transfer(
                    Login.userInfo.get(0),Login.userInfo.get(1),tfnumAcc.getText(),
                    Double.parseDouble(tfamount1.getText()));
                if(loi.isEmpty()){
                    tfbalance.setText(String.valueOf(user.bank.getAccount(Login.userInfo.get(0), Login.userInfo.get(1)).getBalance()));
                    JOptionPane.showMessageDialog(null, "Chuyển khoản thành công", "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                    tfsoduht.setText(tfbalance.getText());
                    lbsodu.setText("Số dư : "+tfbalance.getText()); 
                    tfamount1.setText("");
                }else{
                    String erorr="";
                    for(int i=0;i<loi.size();i++){
                        erorr=loi.get(i)+"\n";
                    }
                    JOptionPane.showMessageDialog(null,erorr, "Warning",
                        JOptionPane.WARNING_MESSAGE);
                }
            } catch (RemoteException | SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btOk2ActionPerformed

    private void btCancelDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelDActionPerformed
        tfpw1.setText("");
        tfpwag1.setText("");
    }//GEN-LAST:event_btCancelDActionPerformed

    private void btsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsave1ActionPerformed
        ArrayList<String> loi = validation();
        if(loi.isEmpty()){
            try {
                user.bank.doimatkhau(Login.userInfo.get(0), Login.userInfo.get(1),tfpw1.getText());
                Login.userInfo.set(2, tfpw1.getText());
                JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                tfpw1.setText("");
                tfpwag1.setText("");
            } catch (RemoteException | SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }     
        }else{
            JOptionPane.showMessageDialog(null, loi.get(0), "Warning",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btsave1ActionPerformed

    private void btCancelRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelRActionPerformed
        tfBalance.setText("");
    }//GEN-LAST:event_btCancelRActionPerformed

    private void btOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOk1ActionPerformed
        if(tfBalance.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Bạn chưa điền đủ thông tin", "Warning",
                JOptionPane.WARNING_MESSAGE);
        }else{
                ArrayList<String> loi;
            try {
                loi = user.bank.withdraw(Login.userInfo.get(0), Login.userInfo.get(1), Double.parseDouble(tfBalance.getText()));
                if(loi.size()>0){
                    String erorr="";
                    for(int i=0;i<loi.size();i++){
                        erorr=loi.get(i)+"\n";
                    }
                    JOptionPane.showMessageDialog(null,erorr, "Warning",
                        JOptionPane.WARNING_MESSAGE);
                }else{
                    tfsoduht.setText(String.valueOf(user.bank.getAccount(Login.userInfo.get(0), Login.userInfo.get(1)).getBalance()));
                    tfbalance.setText(tfsoduht.getText());
                    lbsodu.setText("Số dư : "+tfbalance.getText());
                    JOptionPane.showMessageDialog(null, "Rút tiền thành công", "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                }
                tfBalance.setText("");
            } catch (RemoteException | SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_btOk1ActionPerformed

    private void tfsoduhtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsoduhtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsoduhtActionPerformed

    private void btCancelGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelGActionPerformed
        tfamount.setText("");
    }//GEN-LAST:event_btCancelGActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        if(tfamount.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Bạn chưa điền đủ thông tin", "Warning",
                JOptionPane.WARNING_MESSAGE);
        }else{
            ArrayList<String> loi;
            try {
                loi = user.bank.deposit(Login.userInfo.get(0),Login.userInfo.get(1), Double.parseDouble(tfamount.getText()));
                if(loi.size()>0){
                    String erorr="";
                    for(int i=0;i<loi.size();i++){
                        erorr=loi.get(i)+"\n";
                    }
                    JOptionPane.showMessageDialog(null,erorr, "Warning",
                        JOptionPane.WARNING_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "Gửi tiền thành công", "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                    tfbalance.setText(String.valueOf(user.bank.getAccount(Login.userInfo.get(0), Login.userInfo.get(1)).getBalance()));
                    tfsoduht.setText(tfbalance.getText());
                    lbsodu.setText("Số dư : "+tfbalance.getText());
                }
                tfamount.setText("");
            } catch (RemoteException | SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }     
        }
    }//GEN-LAST:event_btOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (RemoteException | SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack2;
    private javax.swing.JButton btCancelC;
    private javax.swing.JButton btCancelD;
    private javax.swing.JButton btCancelG;
    private javax.swing.JButton btCancelR;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btOk1;
    private javax.swing.JButton btOk2;
    private javax.swing.JButton btsave;
    private javax.swing.JButton btsave1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbaddress;
    private javax.swing.JLabel lbcmnd;
    private javax.swing.JLabel lbnumAcc;
    private javax.swing.JLabel lbphone;
    private javax.swing.JLabel lbresult;
    private javax.swing.JLabel lbsodu;
    private javax.swing.JLabel lbten;
    private javax.swing.JTextField tfBalance;
    private javax.swing.JTextField tfamount;
    private javax.swing.JTextField tfamount1;
    private javax.swing.JTextField tfbalance;
    private javax.swing.JTextField tfnumAcc;
    private javax.swing.JPasswordField tfpw;
    private javax.swing.JPasswordField tfpw1;
    private javax.swing.JPasswordField tfpwag;
    private javax.swing.JPasswordField tfpwag1;
    private javax.swing.JTextField tfsoduht;
    // End of variables declaration//GEN-END:variables
}
