package server_atm;

import common_atm.Account;
import common_atm.User;
import java.rmi.AlreadyBoundException;
import java.rmi.RemoteException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

public class Main extends javax.swing.JFrame {

    Server_ATM server;
    DefaultTableModel tb;

    public Main() throws RemoteException, ClassNotFoundException, SQLException, AlreadyBoundException{
        initComponents();
        setLocationRelativeTo(null);
        init_taotaikhoan();
        server = new Server_ATM();
        server.init(server);
        String[] nameColumn = {"Họ tên", "Địa chỉ", "SĐT", "Số CMND",
                    "Chủ thẻ", "Số pin", "Số tài khoản","Số dư"};
        jTabbedPane1.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if(jTabbedPane1.getSelectedIndex()==2){
                    tb = new DefaultTableModel(nameColumn,0);
                    try {
                        getListAccount();
                    } catch (SQLException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    tblist.setModel(tb);
                }
                if(jTabbedPane1.getSelectedIndex()==3){
                    System.exit(0);
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The server.content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tfTen = new javax.swing.JTextField();
        tfDiachi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbLink = new javax.swing.JLabel();
        rdbtMain = new javax.swing.JRadioButton();
        rdbtPhu = new javax.swing.JRadioButton();
        tfnumAccount = new javax.swing.JTextField();
        tfcmndmain = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btReset = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();
        tfPhone = new javax.swing.JTextField();
        tfcmnd = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tfcmnd1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfnumAccount1 = new javax.swing.JTextField();
        btOk = new javax.swing.JButton();
        btresetx = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblist = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        tfTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenActionPerformed(evt);
            }
        });

        tfDiachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDiachiActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên người dùng : ");

        jLabel2.setText("Địa chỉ               : ");

        jLabel3.setText("Số điện thoại     : ");

        jLabel4.setText("Số cmnd            : ");

        lbLink.setText("liên kết với tài khoản có : ");

        buttonGroup1.add(rdbtMain);
        rdbtMain.setText("chủ thẻ chính");
        rdbtMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtMainActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbtPhu);
        rdbtPhu.setText("chủ thẻ phụ");
        rdbtPhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtPhuActionPerformed(evt);
            }
        });

        tfnumAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnumAccountActionPerformed(evt);
            }
        });

        jLabel5.setText("numAccount : ");

        jLabel6.setText("cmnd            :");

        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        btAdd.setText("Thêm");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        tfPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(lbLink))))
                                .addGap(24, 24, 24))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfDiachi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(tfTen, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(tfcmnd)
                                .addComponent(tfPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfnumAccount)
                                    .addComponent(tfcmndmain, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btReset)
                        .addGap(126, 126, 126))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdbtMain)
                        .addGap(18, 18, 18)
                        .addComponent(rdbtPhu)
                        .addGap(79, 79, 79)))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfDiachi, tfPhone, tfTen, tfcmnd});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAdd, btReset});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfcmnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbtPhu)
                            .addComponent(rdbtMain)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)
                        .addGap(57, 57, 57)
                        .addComponent(lbLink)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfnumAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcmndmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd)
                    .addComponent(btReset))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Tạo tài khoản", jPanel1);

        tfcmnd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcmnd1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Số tài khoản : ");

        jLabel8.setText("Số cmnd       :");

        btOk.setText("Ok");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btresetx.setText("Reset");
        btresetx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfnumAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfcmnd1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btresetx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btOk, btresetx});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfnumAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfcmnd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOk)
                    .addComponent(btresetx))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Xóa tài khoản", jPanel2);

        tblist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Họ tên", "Phone", "Số cmnd", "Địa chỉ", "Số tài khoản", "Mật khẩu", "Chủ thẻ", "Số dư"
            }
        ));
        tblist.setRowHeight(25);
        jScrollPane2.setViewportView(tblist);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Xem danh sách tài khoản", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thoát", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenActionPerformed

    private void tfDiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDiachiActionPerformed

    private void rdbtMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtMainActionPerformed
        tfnumAccount.setEnabled(false);
        tfnumAccount.setText("");
        tfcmndmain.setEnabled(false);
        tfcmndmain.setText("");
    }//GEN-LAST:event_rdbtMainActionPerformed

    private void rdbtPhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtPhuActionPerformed
        tfnumAccount.setEnabled(true);
        tfcmndmain.setEnabled(true);
    }//GEN-LAST:event_rdbtPhuActionPerformed

    private void tfnumAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnumAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnumAccountActionPerformed

    //tạo tài khoản
    private void init_taotaikhoan(){
        rdbtMain.setSelected(true);
        tfnumAccount.setEnabled(false);
        tfcmndmain.setEnabled(false);
    }
    //reset
    private void reset_taotaikhoan(){
        tfDiachi.setText("");
        tfPhone.setText("");
        tfTen.setText("");
        tfcmnd.setText("");
        tfnumAccount.setText("");
        tfcmndmain.setText("");
    }
     //random string
    private String randomString(int size){
        String str01 = "abcdefghijklmnopqrstuvwxyz";
        String str02 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String str03 = "0123456789";
        String strValid = str01 + str02 + str03;
        Random random = new Random();
        
        String mystring = "";
        for( int i=0; i<size; i++ ) {
             int randnum = random.nextInt(strValid.length());
             mystring = mystring + strValid.charAt(randnum);
        } 
        return mystring; 
    }    
     private boolean isExistsNumAccount(String numAccount) throws SQLException{
        String sql="select * from account where account.numAccount =?";
        PreparedStatement ps=server.cont.prepareStatement(sql);
        ps.setString(1,numAccount);
        return ps.executeQuery()==null;
    }
    
    private boolean validateAddAccount(boolean main) throws SQLException{
        if(main){
           if(tfDiachi.getText().equals("")||tfPhone.getText().equals("")
                ||tfTen.getText().equals("")||tfcmnd.getText().equals("")){
                return false;
            }
          
        }else{
            if(tfDiachi.getText().equals("")||tfPhone.getText().equals("")
                ||tfTen.getText().equals("")||tfcmnd.getText().equals("")
                    ||tfnumAccount.getText().equals("")||tfcmndmain.getText().equals("")){
                return false;
            }
        } 
        return true;
    }
    public boolean addAccount(User user,boolean main) throws SQLException, ClassNotFoundException{
        Account acc;
        int id_parent;
        if(main){
            String numAccount;
            do{
                numAccount = randomString(12);
            }while(isExistsNumAccount(numAccount));
            acc =new Account(user.getName(), randomString(6), numAccount, 50000);
            id_parent=0;
        }else{
            if(tfcmndmain.getText().equals(tfcmnd.getText())){ 
                return false;
            }
            double balance = server.getAccount(tfnumAccount.getText(), tfcmndmain.getText()).getBalance();
            id_parent = server.getUser(tfnumAccount.getText(), tfcmndmain.getText()).getId();
            acc =new Account(user.getName(), randomString(6), tfnumAccount.getText(), balance);
        }
        //thêm vào bảng user
        String sql="insert into user(name,address,phone,cmnd,id_parent) values(?,?,?,?,?)";
        PreparedStatement ps;
        ps=server.cont.prepareStatement(sql,PreparedStatement.RETURN_GENERATED_KEYS);
        ps.setString(1, user.getName());
        ps.setString(2, user.getAddress());
        ps.setString(3, user.getPhone());
        ps.setString(4, user.getCmnd());
        ps.setInt(5, id_parent);
        ps.executeUpdate();
        ResultSet rs = ps.getGeneratedKeys();
        int id_user=0;
        if (rs.next()) {
            id_user = rs.getInt(1);
        }
        
        //thêm vào bảng account
        sql="insert into account(username,pin,numAccount,balance) values(?,?,?,?)";
        ps=server.cont.prepareStatement(sql,PreparedStatement.RETURN_GENERATED_KEYS);
        ps.setString(1, acc.getNameUser());
        ps.setString(2, acc.getPin());
        ps.setString(3, acc.getNumAccount());
        ps.setDouble(4, acc.getBalance());
        ps.executeUpdate();
        rs=ps.getGeneratedKeys();
        int id_account=0;
        if (rs.next()) {
            id_account = rs.getInt(1);
        }

        //thêm vào bảng user_account
        sql="insert into user_account(id_user,id_account) values(?,?)";
        ps=server.cont.prepareStatement(sql);
        ps.setInt(1, id_user);
        ps.setInt(2,id_account);
        ps.executeUpdate();
        return true;
    }
    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        try {
            if(validateAddAccount(rdbtMain.isSelected())){
                if(rdbtPhu.isSelected()){
                    if(server.getUser(tfnumAccount.getText(), tfcmndmain.getText())==null){
                        JOptionPane.showMessageDialog(null, "Không có người dùng này", "Warning",
                            JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
                if(addAccount(new User(tfTen.getText(), tfDiachi.getText(),
                    tfPhone.getText(), tfcmnd.getText()),rdbtMain.isSelected())){
                    JOptionPane.showMessageDialog(null, "Thêm tài khoản thành công"
                        ,"Success", JOptionPane.INFORMATION_MESSAGE);
                    reset_taotaikhoan();
                    init_taotaikhoan();
                }else{
                    JOptionPane.showMessageDialog(null, "Không thể tạo tài khoản bằng số cmnd này", "Warning",
                        JOptionPane.WARNING_MESSAGE);
                    tfcmnd.setText("");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Bạn chưa điền đủ thông tin", "Warning",
                    JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Taotaikhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        reset_taotaikhoan();
    }//GEN-LAST:event_btResetActionPerformed

    private void tfcmnd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcmnd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcmnd1ActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        try {
            if(validation()){
                User user = server.getUser(tfnumAccount1.getText(), tfcmnd1.getText());
                if(user==null){
                    JOptionPane.showMessageDialog(null, "Không có người dùng này", "Warning",
                        JOptionPane.WARNING_MESSAGE);
                }else{
                    deleteAccount(user);
                    JOptionPane.showMessageDialog(null, "Xóa tài khoản thành công"
                        ,"Success", JOptionPane.INFORMATION_MESSAGE);
                    reset();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Bạn chưa điền đủ thông tin", "Warning",
                    JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Xoataikhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void tfPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhoneActionPerformed

    private void btresetxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetxActionPerformed
        tfnumAccount1.setText("");
        tfcmnd1.setText("");
    }//GEN-LAST:event_btresetxActionPerformed
    //xóa tài khoản
     private boolean validation(){
        return !(tfnumAccount1.getText().equals("")||tfcmnd1.getText().equals(""));
    }
    
    private void reset(){
        tfcmnd1.setText("");
        tfnumAccount1.setText("");
    }
    private void deleteAccount(User user) throws SQLException{
        String sql;
        PreparedStatement ps;
        if(user.getId_parent()!=0){
            sql = "delete user,account,user_account from user inner join user_account on "
                    + "user.id=user_account.id_user inner join account on "
                    + "user_account.id_account=account.id "
                    + "where user.id=?";
            ps=(server.cont).prepareStatement(sql);
            ps.setInt(1, user.getId());   
            ps.executeUpdate();
        }else{
            sql = "delete user,account,user_account from user inner join user_account on "
                    + "user.id=user_account.id_user inner join account on "
                    + "user_account.id_account=account.id "
                    + "where user.id=? or user.id_parent=?";
            ps=(server.cont).prepareStatement(sql);
            ps.setInt(1, user.getId());
            ps.setInt(2, user.getId());
            ps.executeUpdate();
        }
    }
    //xem danh sách tài khoản
     private void getListAccount() throws SQLException{
        ResultSet rs = server.getListAccount();
        while(rs.next()){
            ArrayList arrayRow = new ArrayList();
            for(int i=1;i<=8;i++){
                if(i==5){
                    if(rs.getInt(i)==0)
                        arrayRow.add("chính");
                    else
                        arrayRow.add("phụ");
                }else if(i==8){
                    arrayRow.add(rs.getDouble(i));
                }else{
                    arrayRow.add(rs.getString(i));
                }
            }
            tb.addRow(arrayRow.toArray());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (RemoteException | ClassNotFoundException | SQLException | AlreadyBoundException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btresetx;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbLink;
    private javax.swing.JRadioButton rdbtMain;
    private javax.swing.JRadioButton rdbtPhu;
    private javax.swing.JTable tblist;
    private javax.swing.JTextField tfDiachi;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfTen;
    private javax.swing.JTextField tfcmnd;
    private javax.swing.JTextField tfcmnd1;
    private javax.swing.JTextField tfcmndmain;
    private javax.swing.JTextField tfnumAccount;
    private javax.swing.JTextField tfnumAccount1;
    // End of variables declaration//GEN-END:variables
}
