/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server_atm;

import java.rmi.AlreadyBoundException;
import java.rmi.RemoteException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class Xemdanhsachtaikhoan extends javax.swing.JFrame {

     DefaultTableModel tb;
     Server_ATM server;
    /**
     * Creates new form Xemdanhsachtaikhoan
     */
    public Xemdanhsachtaikhoan() throws SQLException, ClassNotFoundException {
        initComponents();
        setLocationRelativeTo(null);
         try {
            server = new Server_ATM();
        } catch (RemoteException ex) {
            Logger.getLogger(Xoataikhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        String[] nameColumn = {"Họ tên", "Địa chỉ", "SĐT", "Số CMND",
            "Chủ thẻ", "Số pin", "Số tài khoản","Số dư"};
        tb = new DefaultTableModel(nameColumn,0);
        getListAccount();
        tblist.setModel(tb);
    }
    private void getListAccount() throws SQLException{
        ResultSet rs = server.getListAccount();
//        ResultSetMetaData rsm = rs.getMetaData();
//        int numColumn = rsm.getColumnCount();
//        ArrayList<String> arrayColumn = new ArrayList<>();
//        for(int i=1; i<= numColumn;i++){
//            if(i==5){
//                arrayColumn.add("chủ thẻ");
//            }else{
//                arrayColumn.add(rsm.getColumnName(i));
//            }
//        }
//        tb.setColumnIdentifiers(arrayColumn.toArray());
        while(rs.next()){
            ArrayList arrayRow = new ArrayList();
            for(int i=1;i<=8;i++){
                if(i==5){
                    if(rs.getInt(i)==0)
                        arrayRow.add("chính");
                    else
                        arrayRow.add("phụ");
                }else if(i==8){
                    arrayRow.add(rs.getDouble(i));
                }else{
                    arrayRow.add(rs.getString(i));
                }
            }
            tb.addRow(arrayRow.toArray());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblist = new javax.swing.JTable();
        btBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Họ tên", "Phone", "Số cmnd", "Địa chỉ", "Số tài khoản", "Mật khẩu", "Chủ thẻ", "Số dư"
            }
        ));
        jScrollPane1.setViewportView(tblist);

        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btBack)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
         try {
             new GUI().setVisible(true);
             dispose();
         } catch (RemoteException ex) {
             Logger.getLogger(Xemdanhsachtaikhoan.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(Xemdanhsachtaikhoan.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(Xemdanhsachtaikhoan.class.getName()).log(Level.SEVERE, null, ex);
         } catch (AlreadyBoundException ex) {
             Logger.getLogger(Xemdanhsachtaikhoan.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_btBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Xemdanhsachtaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Xemdanhsachtaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Xemdanhsachtaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Xemdanhsachtaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Xemdanhsachtaikhoan().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Xemdanhsachtaikhoan.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Xemdanhsachtaikhoan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblist;
    // End of variables declaration//GEN-END:variables
}
